[[sudoku]]
row = ["5", "3", "",  "", "7", "", "", "", ""]
[[sudoku]]
row = ["6", "",  "",  "1", "9", "5", "", "", ""]
[[sudoku]]
row = ["", "9", "8",  "", "", "", "", "6", ""]
[[sudoku]]
row = ["8", "", "", "", "6", "", "", "", "3"]
[[sudoku]]
row = ["4", "", "", "8", "", "3", "", "", "1"]
[[sudoku]]
row = ["7", "", "", "", "2", "", "", "", "6"]
[[sudoku]]
row = ["", "6", "", "", "", "", "2", "8", ""]
[[sudoku]]
row = ["", "", "", "4", "1", "9", "", "", "5"]
[[sudoku]]
row = ["", "", "", "", "8", "", "", "7", "9"]

[[area]]
fields = [[0,0], [0,1], [1,1], [1, 2]]
value = 17

