[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]
[[sudoku]]
row = ["", "", "", "", "", "", "", "", ""]

[[area]]
fields = [[0,0]]
value = 6

[[area]]
fields = [[0,1], [0,2]]
value = 13

[[area]]
fields = [[0,3], [0,4], [1,4]]
value = 9

[[area]]
fields = [[0,5], [1,5]]
value = 10

[[area]]
fields = [[0,6], [0,7]]
value = 11

[[area]]
fields = [[0,8], [1,7], [1,8]]
value = 17

[[area]]
fields = [[1,0], [2,0]]
value = 9

[[area]]
fields = [[1,1], [2,1]]
value = 4

[[area]]
fields = [[1,2], [2,2]]
value = 13

[[area]]
fields = [[1,3], [2,3], [2,4]]
value = 22

[[area]]
fields = [[1,6], [2,6]]
value = 6

[[area]]
fields = [[2,5], [3,5], [3,6]]
value = 20

[[area]]
fields = [[2,7], [3,7]]
value = 4

[[area]]
fields = [[2,8], [3,8]]
value = 11

[[area]]
fields = [[3,0], [4,0], [5,0]]
value = 9

[[area]]
fields = [[3,1], [4,1]]
value = 10

[[area]]
fields = [[3,2], [3,3], [3,4]]
value = 14

[[area]]
fields = [[4,2], [5,1], [5,2]]
value = 18

[[area]]
fields = [[4,3], [4,4]]
value = 10

[[area]]
fields = [[4,5], [5,5]]
value = 8

[[area]]
fields = [[4,6], [5,6]]
value = 8

[[area]]
fields = [[4,7], [4,8]]
value = 15

[[area]]
fields = [[5,3], [6,3]]
value = 15

[[area]]
fields = [[5,4], [6,4], [6,5]]
value = 15

[[area]]
fields = [[5,7]]
value = 5

[[area]]
fields = [[5,8], [6,8]]
value = 9

[[area]]
fields = [[6,0], [6,1]]
value = 11

[[area]]
fields = [[6,2], [7,0], [7,1], [7,2], [8,0]]
value = 24

[[area]]
fields = [[6,6], [6,7], [7,6]]
value = 14

[[area]]
fields = [[7,3], [8,3], [8,4]]
value = 11

[[area]]
fields = [[7,4], [7,5], [8,5]]
value = 18

[[area]]
fields = [[7,7], [8,7], [8,6]]
value = 19

[[area]]
fields = [[7,8], [8,8]]
value = 7

[[area]]
fields = [[8,1], [8,2]]
value = 10
