[[sudoku]]
row = ["", "2", "",  "", "", "", "", "", ""]
[[sudoku]]
row = ["8", "",  "",  "", "", "", "6", "", "9"]
[[sudoku]]
row = ["", "9", "",  "", "3", "1", "", "", ""]
[[sudoku]]
row = ["", "", "", "3", "", "", "", "", ""]
[[sudoku]]
row = ["7", "3", "6", "", "", "", "1", "", ""]
[[sudoku]]
row = ["", "8", "2", "", "1", "6", "3", "7", ""]
[[sudoku]]
row = ["", "", "8", "", "", "9", "", "5", ""]
[[sudoku]]
row = ["1", "7", "", "8", "", "", "", "", ""]
[[sudoku]]
row = ["3", "", "", "", "", "", "2", "", ""]

[[area]]
fields = [[0,0], [0,1]]
value = 8




[[area]]
fields = [[0,2], [1,2]]
value = 10

[[area]]
fields = [[0,3], [1,3], [0,4]]
value = 15

[[area]]
fields = [[0,5], [0,6]]
value = 13

[[area]]
fields = [[0,7], [0,8]]
value = 4

[[area]]
fields = [[1,0], [2,0]]
value = 13

[[area]]
fields = [[1,1], [2,1]]
value = 10

[[area]]
fields = [[1,4], [1,5]]
value = 12

[[area]]
fields = [[1,6], [2,5], [2,6], [3,6]]
value = 24

[[area]]
fields = [[1,7], [2,7]]
value = 6

[[area]]
fields = [[1,8], [2,8], [3,8]]
value = 18

[[area]]
fields = [[2,2], [3,1], [3,2]]
value = 10

[[area]]
fields = [[2,3], [3,3]]
value = 9

[[area]]
fields = [[2,4], [3,4], [3,5]]
value = 18

[[area]]
fields = [[3,0], [4,0]]
value = 11

[[area]]
fields = [[3,7], [4,7], [5,7]]
value = 21

[[area]]
fields = [[4,1], [5,1], [4,2], [4,3]]
value = 21

[[area]]
fields = [[4,4], [5,4]]
value = 10

[[area]]
fields = [[4,5], [4,6]]
value = 3

[[area]]
fields = [[4,8], [5,8]]
value = 9

[[area]]
fields = [[5,0]]
value = 9

[[area]]
fields = [[5,2], [5,3]]
value = 7

[[area]]
fields = [[5,5], [5,6], [6,6], [7,6]]
value = 20

[[area]]
fields = [[6,0], [7,0], [7,1], [8,0]]
value = 13

[[area]]
fields = [[6,1], [6,2], [7,2]]
value = 17

[[area]]
fields = [[6,3]]
value = 1

[[area]]
fields = [[6,4], [6,5]]
value = 15

[[area]]
fields = [[6,7], [6,8], [7,7]]
value = 17

[[area]]
fields = [[7,3], [7,4], [7,5], [8,4]]
value = 18

[[area]]
fields = [[7,8], [8,8], [8,7]]
value = 15

[[area]]
fields = [[8,1], [8,2], [8,3]]
value = 22

[[area]]
fields = [[8,5], [8,6]]
value = 6
